version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  integration_test:
    image: docker/compose:1.27.4
    volumes:
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["up", "--exit-code-from", "test_runner"]
    working_dir: /code
    depends_on:
      - jenkins

networks:
  net: